### ISSUE TITLE
research O flag

### ISSUE THREAD

**Issue by tofixx** [tofixx/epic-battle-db#7]

**Comment by tofixx** [comment]
test different O Flags 1-4 and check what is the fastest for all tests executed

**Comment by maxklenk** [comment]
I tried the flags but first our test measurement results have to be more stable, I can't see a clear difference as long as the test timings are not comparable.

**Comment by maxklenk** [comment]
The reproduce what I tested please run the branch [feature/test-O-flags](https://github.com/tofixx/epic-battle-db/tree/feature/test-O-flags)

**Comment by maxklenk** [comment]
Also have a look a the the build results in the CI, the environment there is more controlled (clean machine) so the tests results can be compared better: https://travis-ci.org/tofixx/epic-battle-db/builds/242687880
